<?php
/**
 * @file Provides sample scripts that demonstrate the capabilities of the VoIP Drupal platform
 */ 

/**
 * Implementation of hook_voipscript_load_script()
 */
function vozmob_callin_voipscript_load_script($script_name, $params=NULL) {
  if ($script_name == 'vozmob_callin_record_script') {
    return _vozmob_callin_load_script();
  }
}

/**
 * Implementation of hook_voipscript_get_script_names()
 */
function vozmob_callin_voipscript_get_script_names() {
  return array('vozmob_callin_record_script');
}

/*
 * Sample scripts that highlight VoIP Drupal capabilities
 */
function _vozmob_callin_load_script() {
  $script = new VoipScript('vozmob_callin_record_script');

  $script->addLabel('switch_to_spanish');
  $script->addSet('spanishmsg', url(drupal_get_path('module', 'vozmob_callin') . '/audio/VozMob-Bienven-Es-mono.mp3', array('absolute' => TRUE, 'language' => (object) array('prefix' => '', 'domain' => $GLOBALS['language']->domain))));
  $script->addGetInput('%spanishmsg', 1, '', 1);
  $script->addGotoIf('switch_to_english', "^%input_digits == '2'");
  $script->addGoto('start_recording');

  $script->addLabel('switch_to_english');
  $script->addSet('language', 'en');
  $script->addSet('englishmsg', url(drupal_get_path('module', 'vozmob_callin') . '/audio/VozMob-Welcome-En-mono.mp3', array('absolute' => TRUE, 'language' => (object) array('prefix' => '', 'domain' => $GLOBALS['language']->domain))));
  $script->addSay('%englishmsg');

  $script->addLabel('start_recording');
  $timeout = 15;
  $end_key = '#';
  $max_length = 1000;
  $prompt = t("Please record your message. When done, press the pound key.");
  $script->addRecord($prompt, $timeout, $end_key, $max_length);
  $script->addGotoIf('switch_to_english', "^%recording_digits == '2'");
  // if recording return 0 don't save
  $script->addGotoIf('no recording detected', '^%recording_duration == 0');

  // otherwise just save
  $script->addSet('callback_result', '^_vozmob_callin_record_callback(%call_id, %recording_fid, %recording_duration, %caller_number, %language)');
  $script->addGoto('end call');

  $script->addLabel('no recording detected');
  $script->addSay("No recording detected. Please try again.");
  $script->addGoto('start_recording');

  $script->addLabel('end call');
  $script->addSay('Bye bye.');
  $script->addHangup();

  return $script;
}

/**
 * Callback function associated with the script vozmob_callin_record_script.
 * It is called whenever that script records a new entry from the user.
 */
function _vozmob_callin_record_callback($call_id, $fid, $recording_duration, $caller_number, $language) {
  watchdog('vozmob_callin', 'in _vozmob_callin_record_callback(%call_id, %recording_fid, %recording_duration, %caller_number, %english_msg)', array('%call_id' => $call_id, '%recording_fid' => $fid, '%recording_duration' => $recording_duration, '%caller_number' => $caller_number, '%english_msg' => $language));

  // If no language came across, user did not specify english, so use site default (es).
  if (!$language) {
    $language = language_default('language');
  }
  // Get user info based on the number they called in with.
  $uid = sms_user_get_uid($caller_number);
  // there is some wackiness with phone numbers in sms_user table.  Sometimes
  // a phone number comes in as 11 digits, with a 1 digit country code at
  // the beginning. If the number is 11 digits and no uid is set, do another
  // lookup after removing the first digit.
  if (!$uid && strlen($caller_number) == 11) {
    watchdog('vozmob_callin', '11 digit number detected');
    $mod_number = substr($caller_number, 1);
    $uid = sms_user_get_uid($mod_number);
    // if no user is still found, we need to create the new user without
    // the country code. otherwise it will create a different account
    // without the country code when a user sends an sms to the system.
    if (!$uid) {
      $caller_number = $mod_number;
    }
    else {
      watchdog('vozmob_callin', 'found user with modified number: %uid', array('%uid' => $uid));
    }
  }
  
  watchdog('vozmob_callin', 'found user %uid for %caller_number', array('%uid' => $uid, '%caller_number' => $caller_number));

  // create a new user if phone number isn't in database
  while (!$uid) {
    $user = user_save(NULL, array(
      'name' => variable_get('sms_registration_username', 'Drupal-') . mt_rand(1, db_result(db_query('SELECT MAX(uid) FROM {users}')) * 10),
      'pass' => user_password(8),
      'mail' => $_REQUEST['From'],
      'roles' => ($role = variable_get('sms_registration_role', NULL)) ? array($role => 1) : NULL,
      'status' => 1,
      'language' => $language,
      'sms_user' => array('number' => sms_formatter($caller_number), 'status' => SMS_USER_PENDING, 'gateway' => array()),
    ));
    if ($user) {
      $uid = $user->uid;
    }
  }

  // Construct the new node object.
  $node = new stdClass();
  $result = db_query('SELECT * FROM {files} WHERE fid = %d', $fid);
  if ($file = db_fetch_object($result)) {
    $file->list = variable_get('upload_list_default', 1);
    $node->files[$file->fid] = $file;
    // Force upload module to recognize the file attachment.
    $node->old_vid = 1;
  }
  $node->title = t('Voice message');
  $node->body = '';
  $node->type = 'blog';
  $node->created = $_SERVER['REQUEST_TIME'];
  $node->changed = $node->created;
  $node->status = 1;
  $node->promote = 0;
  $node->sticky = 0;
  $node->format = 1;
  $node->uid = $uid;
  $node->language = $language;
  $node = node_submit($node);
  node_save($node);
  return 'Success';
}
