<?php

require_once(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'voipvoicelocal.inc');

/**
 * Implementation of hook_menu()
 */
function voipvoice_menu() {
  $items = array();

  $items['admin/settings/voipvoice'] = array(
    'title' => 'VoIP Voice',
    'description' => 'VoIP Voice landing page',
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('manage voip voices'),
   );
   
   $items['admin/settings/voipvoice/voices'] = array(
    'title' => 'Manage VoIP voices',
    'description' => 'Manage VoIP voices',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_manage_voices'),
    'access arguments' => array('manage voip voices'),
    'type' => MENU_NORMAL_ITEM,
   );
   
  $items['admin/settings/voipvoice/voices/%'] = array(
    'title' => 'Edit VoIP voice',
    'description' => 'Manage VoIP voices',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_add_voice',4),
    'access arguments' => array('manage voip voices'),
  );
  
  $items['admin/settings/voipvoice/voices/recordings/%'] = array(
    'title' => 'VoIP recordings for !voice ',
    'title arguments' => array('!voice' => 5),
    'description' => 'Manage VoIP recordings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_manage_recordings_form',5),
    'access arguments' => array('manage voip voices'),
  ); 
  
  $items['admin/settings/voipvoice/voices/overview'] = array(
    'title' => 'List',
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['admin/settings/voipvoice/voices/add'] = array(
    'title' => 'Add voice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_add_voice'),
    'access arguments' => array('manage voip voices'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  
  $items['admin/settings/voipvoice/voices/import'] = array(
    'title' => 'Import voice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_import_voice'),
    'access arguments' => array('manage voip voices'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  ); 
  
  $items['admin/settings/voipvoice/export/%'] = array(
    'title' => 'Export voice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_export_voice', 4),
    'access arguments' => array('manage voip voices'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/settings/voipvoice/export-zip/%'] = array(
    'title' => 'Export voice as zip',
    'page callback' => 'voipvoice_export_voice_zip',
    'page arguments' => array(4),
    'access arguments' => array('manage voip voices'),
    'weight' => 1,
  );
  
  $items['admin/settings/voipvoice/voice-advanced/%/%'] = array(
    'title' => 'Voice advanced',
    'page callback' => 'voipvoice_voice_advance',
    'page arguments' => array(4, 5),
    'access arguments' => array('manage voip voices'),
    'weight' => 1,
  );
  
 /* $items['voipvoice/lexicons'] = array(
    'title' => 'AJAX Autocomplete callback',
    'page callback' => 'voipvoice_lexicons_ajax',
    'access arguments' => array('manage voip voices'),
  );
*/
  $items['admin/settings/voipvoice/settings'] = array(
    'title' => 'General settings',
    'description' => 'General settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_general_settings_form'),
    'access arguments' => array('manage voip voices'),
    'type' => MENU_NORMAL_ITEM,
  );


  $items['admin/settings/voipvoice/lexicons/overview'] = array(
    'title' => 'List',
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['admin/settings/voipvoice/lexicons'] = array(
    'title' => 'Manage Lexicons',
    'description' => 'Manage Lexicons',
    'page callback' => 'voipvoice_manage_lexicons',
    'access arguments' => array('manage voip voices'),
    'type' => MENU_NORMAL_ITEM,
   );
   
  $items['admin/settings/voipvoice/lexicons/add-phrase/%'] = array(
    'title' => 'Add new phrase',
    'description' => 'Add new phrase to VoIP Voice table',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_add_phrase_form', 5),
    'access arguments' => array('manage voip voices'),
    'type' => MENU_NORMAL_ITEM,
  );
  
 
  $items['admin/settings/voipvoice/lexicons/add'] = array(
    'title' => 'Add Lexicon',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_add_lexicon'),
    'access arguments' => array('manage voip voices'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  
  $items['admin/settings/voipvoice/lexicons/edit/%'] = array(
    'title' => 'Edit Lexicon',
    'description' => 'Edit Lexicon',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_add_lexicon',5),
    'access arguments' => array('manage voip voices'),
  );
  
  $items['admin/settings/voipvoice/lexicons/phrases/%'] = array(
    'title' => 'VoIP phrases for !lexicon',
    'title arguments' => array('!lexicon' => 5),
    'description' => 'List all lexicon phrases',
    'page callback' => 'voipvoice_lexicon_phrases',
    'page arguments' => array(5),
    'access arguments' => array('manage voip voices'),
  ); 
  
  $items['admin/settings/voipvoice/lexicons/delete/%'] = array(
    'title' => 'Delete Lexicon !lexicon',
    'title arguments' => array('!lexicon' => 5),
    'description' => 'Delete Lexicon',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_delete_lexicon_form',5),
    'access arguments' => array('manage voip voices'),
  );
  
  $items['admin/settings/voipvoice/lexicons/delete-phrase/%'] = array(
    'title' => 'Delete Phrase',
    'description' => 'Delete Phrase',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_delete_phrase',5),
    'access arguments' => array('manage voip voices'),
  );
  
  $items['admin/settings/voipvoice/voices/delete/%'] = array(
    'title' => 'Delete Voice !voice',
    'title arguments' => array('!voice' => 5),
    'description' => 'Delete Voice',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voipvoice_delete_voice_form',5),
    'access arguments' => array('manage voip voices'),
  );
 
  return $items;
}


/**
 * Implements hook_perm().
 */
function voipvoice_perm() {
  $perms = array('manage voip voices');
 
  return $perms;
}

/**
 * Implementation of hook_theme().
 */
function voipvoice_theme() {
  return array(
    'voipvoice_manage_voices' => array(
      'arguments' => array('form' => NULL),
    ),
    'voipvoice_manage_recordings_form' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/**
 *
 * voipvoice_get_prompt() for voice translating.
 */
function voipvoice_get_prompt($prompt_string, $args = array(), $voice_code=NULL) {
  $voice_code = isset($voice_code) ? $voice_code : voipvoice_get_default_voice();
  $langcode =  voipvoice_get_language($voice_code);
  $lexicon = voipvoice_get_voice_lexicon($voice_code);
  $prompt_string = trim($prompt_string);
  if (!$args) {
    // translate main string to current language
    $translated_string = t($prompt_string, $args, $langcode);
    _voipvoice_add_phrase($lexicon, $prompt_string);
    $speech = voipvoice_get_audio_phrase($translated_string, $voice_code);
  }
  else {
    //We use locale directly, so that arguments are not inserted
    $translated_string = locale($prompt_string, $langcode);
    //save the string into the database
    _voipvoice_add_phrase($lexicon, $prompt_string, $args);
    // first add a "split-token" right before and after each replacement mark
    $token = '_vio_' . mt_rand();
    $tokenized_keys = array();
    foreach(array_keys($args) as $key) {
          $tokenized_keys[$key] = "$token$key$token";
    }
    $tokenized_string = strtr($translated_string, $tokenized_keys);
    // then split the string into an array of text chunks and arguments
    $speech_array = explode($token, $tokenized_string);
    
    // replace each element of the array by either an argument provided
    //   or by the name of an already recorded file
    foreach ($speech_array as $index => $phrase) {
      if (!$phrase) {
        unset($speech_array[$index]);
      }
      else if (($phrase{0} == '%') && (array_key_exists($phrase, $args))) {
        $speech_array[$index] = $args[$phrase];
      }
      else {
        $speech_array[$index] = voipvoice_get_audio_phrase($phrase, $voice_code); 
      }
    }
    $speech = implode(" ", $speech_array);
  }
  
  if ($voice_code == 'log') {
    watchdog('voipvoice', "voipvoice_get_prompt() called with prompt_string=$prompt_string , returned with speech=$speech");
  }
  return $speech;
}

/*
 * Create a database entry for a phrase
 */
function _voipvoice_add_phrase($lexicon, $original_phrase, $args = array(), $hash = NULL) {
  //Store hash of original phrase
  if (!$hash) {
    $hash = md5($original_phrase);
  }

  $exists = db_result(db_query("SELECT pid FROM {voipvoice_phrases} WHERE lexicon='%s' AND phrase_hash='%s'", $lexicon, $hash));
  if (!$exists) {
    // add the new string
    // we always same original
    $serialized_args = serialize($args);
    $res = db_query("INSERT INTO {voipvoice_phrases} (phrase_hash, phrase, lexicon, args) VALUES('%s', '%s', '%s', '%s')", $hash, $original_phrase, $lexicon, $serialized_args);
  }
 
  return $res;
}

function voipvoice_get_audio_phrase($phrase, $voice_code) {
  $rc = $phrase;
  $phrase_tmp = trim($phrase);
  if($phrase_tmp != '') {
    $phrase_hash = md5($phrase_tmp);
    $phrase_file_name = voipvoice_recording_exists($voice_code, $phrase_hash);
    // replace phrase by the file
    if ($phrase_file_name) {
      $rc = file_create_url($phrase_file_name);
      //Update the access time without updating the modified time:
      touch($phrase_file_name, date('U', filemtime($phrase_file_name)), time());
    }
  }
  return $rc;
}

/**
 * Implements hook_voip_getvoices().
 */
function voipvoice_voip_getvoices($language , $gender, $is_local, $voice_provider){
  if($is_local === FALSE) {
    //This module doesn't declare non-local voices
    return array();
  }
  
  if($voice_provider) {
    //This module is not voice provider
    return array();
  }
  
  $voices = voipvoice_get_voices($language, $gender);
  //We need to adjust associate array
  foreach($voices as $key => $voice) {
    if ($key == "log") {
      continue;
    }
    $voipvoices[$key] = new VoipVoiceLocal($key, $voice['gender'], $voice['language'], $voice['description']);
  }
  return $voipvoices;
}

/*API Functions*/
/**
 * Creates new VoIP voice
 *
 * @param $voice
 *   Array representing the voice to be added
 *
 * @return
 *   boolean indicating success or failure to add new VoIP voice
 */
function voipvoice_create_voice($voice) {
   $voice_path = file_create_path(file_directory_path() . '/' . variable_get('voipvoice_directory', 'voipvoice').'/'.$voice['name']);
   $file_res = file_check_directory($voice_path, FILE_CREATE_DIRECTORY);
   if(!$file_res) {
     drupal_set_message('The directory '.$voice_path.' couldn\'t be created. Check file permissions.');
     //return;
   }
   $res = @drupal_write_record('voipvoice_voices', $voice);
   return $res;          
}

/**
 * Deletes a VoIP voice
 *
 * @param $voice_code
 *   String representing the voice code
 *
 * @return
 *   Boolean indicating success or failure to delete VoIP voice
 */
function voipvoice_delete_voice($voice_code) {
  $voice_dir = _voipvoice_get_voice_dir($voice_code);
  //Delete all voice recordings
  _voip_voice_delete_dir($voice_dir);
  //Delete voice from database
  $res = db_query("DELETE FROM {voipvoice_voices} WHERE name='%s'", $voice_code);
  
  if ($res) {
    drupal_set_message('Voice '.$voice_code.' sucessfully deleted.');
  }
  else {
    drupal_set_message('VoIP Voice couldn\'t be deleted.', 'error');
  }
  return $res;
}

/**
 * Returns a VoIP voice array
 *
 * @param $voice_code
 *   String representing the voice code
 *
 * @return
 *   Array representing the voice
 */
function voipvoice_get_voice($voice_code) {
  $voice = db_fetch_array(db_query("SELECT * FROM {voipvoice_voices} WHERE name='%s'", $voice_code));
  return $voice;
}

/**
 * Import voice recordings from ZIP archive
 *
 * @param $zip_archive
 *   String representing absolute path to the ZIP archive
 *
 * @param $voice_code
 *   String representing the voice code to which voice recordings will be added
 *
 * @return
 *   Boolean indicating success or failure to import VoIP voice recordings
 */
function voipvoice_import_voices($zip_archive, $voice_id) {
  $zip = new ZipArchive;
  $res = $zip->open($zip_archive);
  if ($res === TRUE) {
    $zip->extractTo(file_directory_path(). '/' . variable_get('voipvoice_directory', 'voipvoice').'/'.$voice_id);
    $zip->close();
    drupal_set_message(t('VoIP Voices sucessfully extracted'));
  }
  else {
    drupal_set_message(t('Error extracting voices. You can try either to re-export voices again or to manually 
    copy voices in appropriate voice directory.'));
  }
  return $res;
}

/**
 * Returns array representing Lexicon
 *
 * @param $lexicon_name
 *   String representing lexicon name
 *
 *
 * @return
 *   Array representing the lexicon
 */
function voipvoice_get_lexicon($lexicon_name) {
  $lexicon = db_fetch_array(db_query("SELECT * FROM {voipvoice_lexicons} WHERE lexicon='%s'", $lexicon_name));
  return $lexicon;
}

/**
 * Creates new lexicon
 *
 * @param $lexicon
 *    Array representing the lexicon to be added
 *
 * @return
 *    Boolean indicating success or failure to add new lexicon
 */
function voipvoice_create_lexicon($lexicon) {
   $res = @drupal_write_record('voipvoice_lexicons', $lexicon);
   return $res;          
}

/**
 * Deletes a lexicon
 *
 * @param $lexicon_name
 *    String representing the lexicon name
 *
 * @return
 *    Boolean indicating success or failure to delete lexicon
 */
function voipvoice_delete_lexicon($lexicon_name) {
  db_query("DELETE FROM {voipvoice_phrases} WHERE lexicon='%s'", $lexicon_name);
  
  $res = db_query("SELECT name FROM {voipvoice_voices} WHERE lexicon='%s'", $lexicon_name);
  while ($voice_code = db_result($res)) {
    //Delete all voices of this lexicon
    voipvoice_delete_voice($voice_code);
  }
  db_query("DELETE FROM {voipvoice_lexicons} WHERE lexicon='%s'", $lexicon_name);
  drupal_set_message('Lexicon '.$lexicon_name.' sucessfully deleted');
}

/**
 * Returns array of phrases belonging to given voice code
 *
 * @param $voice_code
 *   String representing the voice code
 *
 * @return
 *    Array of phrase arrays belonging to given voice code
 */
function voipvoice_get_phrases($voice_code) {
  $lexicon = voipvoice_get_voice_lexicon($voice_code);
 
  $res = db_query("SELECT * FROM {voipvoice_phrases} WHERE lexicon='%s'", $lexicon);
  while ($phrase = db_fetch_array($res)) {
    $phrases[] = $phrase;
  }

  return $phrases;
}

/**
 * Import phrases from phrase array
 *
 * @param $phrases
 *   Array of phrase arrays
 */
function voipvoice_import_phrases($phrases) {
  $failed =0;
  foreach($phrases as $phrase) {
    $res = _voipvoice_add_phrase($phrase['lexicon'], $phrase['phrase'], unserialize($phrase['args']), $phrase['phrase_hash']);
    if(!$res) {
      $failed++;
    }
  }
  $imported = count($phrases) - $failed;
  drupal_set_message('Imported '.$imported.' new phrases.');
}



function voipvoice_recording_exists($voice_code, $phrase_hash) {
  $new_voice_dir = _voipvoice_get_voice_dir($voice_code);
  $extensions = variable_get('voipvoice_allowed_extensions', array('wav' => 'wav'));
  foreach($extensions as $extension) {
    $phrase_file_name = $new_voice_dir . $phrase_hash . '.' . $extension;
    if (file_exists("$phrase_file_name")) {
       return $phrase_file_name;        
    }
  }
  
  return FALSE;
}

/*Returns lexicon of the voice*/
function voipvoice_get_voice_lexicon($voice_code) {
  $lexicon = db_result(db_query("SELECT lexicon FROM {voipvoice_voices} WHERE name='%s'", $voice_code));
  return $lexicon;
}

function voipvoice_get_voices($language=NULL, $gender=NULL) {
  $voices = array();
  if ($language) {
    $where[] = "language='$language'";
  }
  
  if ($gender) {
    //TODO check about neutral
    $where[] = "gender='$gender' OR gender='neutral'";
  }
  
  if($where) {
    $where_query = 'WHERE '. implode(' AND ', $where);
  }
  
  $res = db_query("SELECT * FROM {voipvoice_voices} $where_query ORDER BY language, name");
  while ($voice = db_fetch_array($res)) {
    $voices[$voice['name']] = $voice ;
  }
  return $voices;      
}

/* Returns langcode of voice base language*/
function voipvoice_get_language($voice_code) {
  $voices = voipvoice_get_voices();
  if (isset($voices[$voice_code])) {
    return $voices[$voice_code]['language'];
  }
  
  return NULL;
}

function voipvoice_get_default_voice() {
  return variable_get('voipvoice_default', 'log');
}
/*
function voipvoice_get_default_man_voice() {
  return variable_get('voipvoice_default_man', '');
}

function voipvoice_get_default_woman_voice() {
  return variable_get('voipvoice_default_woman', '');
}
*/

function voipvoice_manage_voices(&$form_state) {
  $voices = voipvoice_get_voices();
  
  foreach($voices as $id=>$voice) {
    $options[$id] = '';
    $form[$id]['id'] = array('#value' => $id);
    $form[$id]['name'] = array('#value' => $id);
    $form[$id]['gender'] = array('#value' => $voice['gender']);
    $form[$id]['lexicon'] = array('#value' => $voice['lexicon']);
    $form[$id]['language'] = array('#value' => locale_language_name($voice['language']).' ('.$voice['language'].')');
    //TODO: Type is hardcoded now
    $form[$id]['type'] = array('#value' => t('User created'));
    $form[$id]['setup'] = array('#value' => l(t('setup'), 'admin/settings/voipvoice/voices/'.$id));
    $form[$id]['recordings'] = array('#value' => l(t('recordings'), 'admin/settings/voipvoice/voices/recordings/'.$id));
    $form[$id]['export'] = array('#value' => l(t('export'), 'admin/settings/voipvoice/export/'.$id));
    $form[$id]['delete'] = array('#value' => l(t('delete'), 'admin/settings/voipvoice/voices/delete/'.$id));
    $form['default'] = array('#type' => 'radios', '#options' => $options, '#default_value' => voipvoice_get_default_voice());
  }

  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Save'),
  );
  
  return $form;
}

function theme_voipvoice_manage_voices($form) {
  $rows = array();
  foreach ($form as $name => $element) {
    if (isset($element['id']) && is_array($element['id'])) {
      $rows[] = array(
        drupal_render($form['default'][$element['id']['#value']]),
        check_plain($element['name']['#value']),
        drupal_render($element['gender']),
        drupal_render($element['lexicon']),
        drupal_render($element['language']),
        drupal_render($element['type']),
        drupal_render($element['setup']),
        drupal_render($element['recordings']),
        drupal_render($element['export']),
        drupal_render($element['delete']),
      );
      unset($form[$name]);
    }
  }
  $header = array(t('Default'), t('Name'), t('Gender'), t('Lexicon'), t('Language'), t('Type'), t('Operations'), t('Recordings'),t('Export'), t('Delete'));
  $output .= theme('table', $header, $rows);
  $output .= drupal_render($form);

  return $output;
}

function voipvoice_manage_voices_submit(&$form, &$form_state) {
  variable_set('voipvoice_default', $form_state['values']['default']);
  drupal_set_message('Default VoIP voice set sucessfully');
}

function voipvoice_add_voice(&$form_state, $voice=NULL) {
  
  if ($voice) {
    $voice_data = db_fetch_array(db_query("SELECT * FROM {voipvoice_voices} WHERE name='%s'", $voice));
    $name = $voice_data['name'];
    $gender = $voice_data['gender'];
    $description = $voice_data['description'];
    $base_language = $voice_data['language'];
    $lexicon = $voice_data['lexicon'];
    $form_state['isupdate'] = TRUE;
  }
  
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Voice Name'),
    '#required' => TRUE,
    '#value' => $name,
    '#disabled' => TRUE,
  );
  $installed_languages = language_list();
  foreach ($installed_languages as $key=>$l) {
    $select_language[$key] = $l->name;
  }
  
  $lexicons = voipvoice_lexicons();
  $form['lexicon'] = array(   
    '#type' => 'select',   
    '#title' => t('Lexicon'),
    '#options' => $lexicons,
    '#default_value' => $lexicon,
    '#required' => TRUE,
  ); 
  
  $form['language'] = array(
    '#type' => 'select',
    '#title' => t('Voice Language'),
    '#options' => $select_language,
    '#required' => TRUE,
    '#default_value' => $base_language,
  );

  $form['gender'] = array(
    '#type' => 'select',
    '#title' => t('Gender'),
    '#options' => array('man' => 'man', 'woman' =>'woman', 'neutral' =>'neutral'),
    '#required' => TRUE,
    '#default_value' => $gender,
  );
  
  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#default_value' => $description,
  );
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Save'),
  );
  return $form;
}

function voipvoice_add_voice_submit(&$form, &$form_state) {
  $name = $form_state['values']['name'];
  $language = $form_state['values']['language'];
  $lexicon = $form_state['values']['lexicon'];
  $gender = $form_state['values']['gender'];
  $description = $form_state['values']['description'];
  
  //Create voice directory
  $voice_path = file_create_path(file_directory_path() . '/' . variable_get('voipvoice_directory', 'voipvoice').'/'.$name);
  $file_res = file_check_directory($voice_path, FILE_CREATE_DIRECTORY);
  if(!$file_res) {
     drupal_set_message('The directory '.$voice_path.' couldn\'t be created. Check file permissions.');
     return;
  }
  $res = db_query("INSERT INTO {voipvoice_voices} (name, language, gender, description, lexicon) VALUES('%s', '%s', '%s', '%s', '%s') 
                   ON DUPLICATE KEY UPDATE language ='%s', gender='%s', description='%s' , lexicon='%s'", $name, $language, $gender, $description, $lexicon, $language, $gender, $description, $lexicon);
  
  //Display appropriate message
  $status = 'status';
  if($form_state['isupdate']) {
    if($res) {
      $message = t('Voice sucessfully updated.');
    }
    else {
     $message = t('Voice couldn\'t be updated. Please try again later.');
      $status = 'error';
    }
  }
  else {
    if($res) {
    $message = t('New voice added.');
  }
  else {
    $message = t('New voice couldn\'t be added. Please try again later.');
    $status = 'error';
  }
  }
  
  drupal_set_message($message, $status);
  $form_state['redirect'] = 'admin/settings/voipvoice/voices';
}

function voipvoice_manage_recordings_form(&$form_state, $voice_code) {
  drupal_add_js(drupal_get_path('module','voipvoice').'/voipvoice.js');
  $recorder = audiorecorderfield_get_recorder();
  $langcode = voipvoice_get_language($voice_code);
  //$new_voice_dir = _voipvoice_get_voice_dir($voice_code);
  $element['#field_name'] = 'voipvoice';
  $lexicon = voipvoice_get_voice_lexicon($voice_code);
  
  //Tab with uploading options (recording and file upload)
  $sources = '<div class="sources-list" style="width:150px"><a class="source-recorder" title="Record audio using default recorder." onclick="return false;" href="#">Audio Recorder</a>
      |<a class="source-upload" title="Upload a file from your computer." onclick="return false;" href="#">Upload</a></div>';
  $max_filesize = file_upload_max_size();
  
  $header = array(
    array(
      'data' => t('Original Phrase'),
      'field' => 'phrase',
      'sort'  => 'asc',
      ),
     );
  //db query
  $sql = "SELECT * FROM {voipvoice_phrases} WHERE lexicon='%s'".tablesort_sql($header);
  //set limit for pager
  $limit = 25;
  $res = pager_query($sql, $limit, 0, NULL, $lexicon);
  

  //foreach($phrases as $phrase) {
  while ($phrase = db_fetch_array($res)) {
    $id = $phrase['pid'];
    $options[$id] = '';
    $form[$id]['id'] = array('#value' => $phrase['pid']);
    $translated_string = t($phrase['phrase'], array(), $langcode);
    //Check for arguments
    $args = unserialize($phrase['args']);
    if (is_array($args) && !empty($args)) {
      //String with arguments
      
      $token = '_vio_' . mt_rand();
      $tokenized_keys = array();
      foreach(array_keys($args) as $key) {
          $tokenized_keys[$key] = "$token$key$token";
      }
      $tokenized_string = strtr($translated_string, $tokenized_keys);
      $translated_string='<div>'.$translated_string.'</div><ul>';
      // then split the string into an array of text chunks and arguments
      $speech_array = explode($token, $tokenized_string);
    
      // replace each element of the array by either an argument provided
      //   or by the name of an already recorded file
      $i=0;
      //Reset the valuess
      $audio_rec = '';
      foreach ($speech_array as $index => $speech_phrase) {
        if($speech_phrase && !(($speech_phrase{0} == '%') && (array_key_exists($speech_phrase, $args)))) {

          $translated_string.="<li>".$speech_phrase."</li>"; 
          $speech_phrase = trim($speech_phrase);
          $phrase_hash = md5($speech_phrase);
          //Fake the element:
          $element['#delta'] = $id.'-'.$i;
          unset($element['#value']);
    
          //check if there is a voice
          $phrase_file_name = voipvoice_recording_exists($voice_code, $phrase_hash);
          $phrase_file = pathinfo($phrase_file_name);
          if ($phrase_file_name) {
            $element['#value']['filepath'] = $phrase_file_name;
            $element['#value']['filename'] = $phrase_hash . "." . $phrase_file['extension'];
          }
               
          $audio_rec .= "<div class='source source-recorder' id='audiorecorderfield-voipvoice-". $id.'-'.$i."-wrapper'>".$recorder['callback']($element, $field['widget'])."</div>";
          // this would be the hidden field the applet would insert the newly uploaded file fid to.
          $form[$id]['fid']['field-voipvoice-'.$id.'-'.$i.'-fid'] = array(
            '#type' => 'hidden',
            '#default_value' => "",
          );
          
          $form[$id]['upload']['upload-'.$id.'-'.$i] = array(
            '#type' => 'file',
            '#title' => t('Click to Upload a recording'),
            '#description' => t('Maximum Filesize: %size', array('%size' => format_size(parse_size($max_filesize)))),
            '#size' => 15,
          ); 
          
          //Store hash
          $form_state['data']['hash-'.$id.'-'.$i] = array(
            '#type' => 'hidden',
            '#value' => $phrase_hash,
          );
          
          $i++;
        }
      }
      $translated_string .= '</ul>';
    }
    else {
      /*String without arguments*/   
      $phrase_hash = md5($translated_string);
      //Fake the element:
      $element['#delta'] = $id;
      unset($element['#value']);
    
      //check if there is a voice
      $phrase_file_name = voipvoice_recording_exists($voice_code, $phrase_hash);
      $phrase_file = pathinfo($phrase_file_name);
      if ($phrase_file_name) {
        $element['#value']['filepath'] = $phrase_file_name;
        $element['#value']['filename'] = $phrase_hash . "." . $phrase_file['extension'];
      }

     
      //$audio_rec = "<div class='voipvoice-uploaders'>".$sources."<div class='source source-recorder' id='audiorecorderfield-voipvoice-".$id."-wrapper'>".$recorder['callback']($element, $field['widget'])."</div>";
      $audio_rec = "<div class='source source-recorder' id='audiorecorderfield-voipvoice-".$id."-wrapper'>".$recorder['callback']($element, $field['widget']).'</div>';
      
      // this would be the hidden field the applet would insert the newly uploaded file fid to.
      $form[$id]['fid']['field-voipvoice-'.$id.'-fid'] = array(
        '#type' => 'hidden',
        '#default_value' => '',
      );
      
       $form[$id]['upload']['upload-'.$id] = array(
         '#type' => 'file',
         '#title' => t('Click to Upload a recording'),
         '#size' => 15,
         '#description' => t('Maximum Filesize: %size', array('%size' => format_size(parse_size($max_filesize)))),
       ); 
      
      //Store hash
      $form_state['data']['hash-'.$id] = array(
       '#type' => 'hidden',
       '#value' => $phrase_hash,
      );
    }
    
    $form[$id]['original_phrase'] = array('#value' =>  $phrase['phrase']);
    if (language_default('language') != $langcode) {
      $form[$id]['translated_phrase'] = array('#value' =>  $translated_string);
    }
    else {
      $form[$id]['translated_phrase'] = array('#value' =>  t('n/a'));
    }
    
    $lid = db_result(db_query("SELECT lid FROM {locales_source} WHERE source='%s'", $phrase['phrase']));
    if (language_default('language') != $langcode) {
      //Display translate link only of voice language is different than default Drupal language
      $form[$id]['translate'] = array('#value' =>  l('translate','admin/build/translate/edit/'.$lid, array('query' => 'destination=admin/settings/voipvoice/voices/recordings/'.$voice_code)));
    }
    else {
      $form[$id]['translate'] = array('#value' =>  t('n/a'));
    }
    
    $form[$id]['advanced'] = array('#value' =>  l('advanced','admin/settings/voipvoice/voice-advanced/'.$voice_code.'/'.$phrase['pid']));
    $form[$id]['applet'] = array(
      '#prefix' => "<div class='voipvoice-uploaders'>",
      '#value' => $sources.$audio_rec,
    );
  }
  
  //store voice code
  $form_state['data']['voice_code'] = $voice_code;
  $form['#attributes'] = array('enctype' => "multipart/form-data"); 
  //pager
  $form['pager'] = array('#value' => theme('pager', NULL, $limit, 0));
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Save'),
  );
  return $form;
}

function voipvoice_manage_recordings_form_submit(&$form,&$form_state) {
  $voice_code = $form_state['data']['voice_code'];
  $new_voice_dir = _voipvoice_get_voice_dir($voice_code);
  $extensions = variable_get('voipvoice_allowed_extensions', array('wav' => 'wav', 'mp3' => '0'));
  /*Save recordings uploaded via recorder*/
  foreach ($form_state['values'] as $key => $fid) {
    if ($fid && strpos($key, 'field-voipvoice') === 0) {
      //Take only voipvoice fields and if they have value
      $pid = str_replace(array('field-voipvoice-', '-fid'), '', $key);
      $hash = $form_state['data']['hash-'.$pid]['#value'];
      
      $file = db_fetch_array(db_query("SELECT * FROM {files} WHERE fid=%d", $fid));
      $phrase_file = pathinfo($file['filepath']);
      $new_filename = $new_voice_dir . $hash . "." . $phrase_file['extension'];
     
     //Delete previous files
      foreach($extensions as $ext) {
        if($ext) {
          $delete_file = $new_voice_dir . $hash . "." . $ext;
          @unlink($delete_file); 
        }
      }

      $success =  rename($file['filepath'], $new_filename);
      if ($success){
        db_query("DELETE FROM {files} WHERE fid = %d", $fid);
      }
      else {
        drupal_set_message("Error saving recorded files.", "error");
      }
    }
  }

  /*Save recordings uploaded via uploader*/
  foreach($_FILES['files']['name'] as $file_key => $filename ) {
    if ($filename) {
      $pid = str_replace('upload-', '', $file_key);
      $hash = $form_state['data']['hash-'.$pid]['#value'];
      
      if ($extensions['mp3'] != "0" && preg_match('!\.(mp3)$!i', $filename)) {
        $extension = 'mp3';
      }
      else if ($extensions['wav'] != "0" && preg_match('!\.(wav)$!i', $filename)) {
        $extension = 'wav';
      }
      else{
        form_set_error($file_key, t('File upload error. Unsupported file type. Only following types are allowed: '. str_replace('0', '', implode(' ', $extensions))));
        continue;
      }
     
      //Delete previous files
      foreach($extensions as $ext) {
        if($ext) {
          $delete_file = $new_voice_dir . $hash . "." . $ext;
          @unlink($delete_file); 
        }
      }
      //Upload new file
      $new_filename = $new_voice_dir . $hash . "." . $extension;
      move_uploaded_file($_FILES['files']['tmp_name'][$file_key], $new_filename);
    } 
  }
}

function theme_voipvoice_manage_recordings_form($form) {
  $rows = array();
 
  foreach ($form as $name => $element) {
    if (isset($element['id']) && is_array($element['id'])) {
      $id = $element['id']['#value'];
      $rows[] = array(
        $element['original_phrase']['#value'],
        $element['translated_phrase']['#value'], 
        drupal_render($element['applet']).drupal_render($element['fid']).'<div class="source source-upload">'.drupal_render($element['upload']).'</div></div>',
        $element['translate']['#value'],
        $element['advanced']['#value'],
      );
      unset($form[$name]);
    }
   
  }
  $header = array(
      array(
        'data' => t('Original Phrase'),
        'field' => 'phrase',
        'sort'  => 'asc',
      ), 
      t('Translated Phrase'), t('Recordings'), t('Translate'), t('Advanced'));
  $output .= theme('table', $header, $rows);
  //$limit = 25;
  //$output .= theme('pager', NULL, $limit, 0);
  $output .= drupal_render($form);

  return $output;
}

function _voipvoice_get_voice_dir($voice_code) {
  return file_directory_path(). '/' .variable_get('voipvoice_directory','voipvoice').'/' . $voice_code . '/';
}

function voipvoice_import_voice() {
   $form['import'] = array(
    '#prefix' => t('This form will import VoIP Voice definitions exported from another site.
Note that VoIP Voices cannot be duplicated, so imported VoIP Voices will be added only if they do not already exist.'),
    '#type' => 'textarea',
    '#title' => t('Import data'),
    '#description' => t('Paste the text created by a VoIP Voice export into this field.'),
    '#cols' => 60,
    '#rows' => 20,
    '#required' => TRUE,
  );
  
  $form['import_voices_zip'] = array(
    '#type' => 'file',
    '#title' => t('Upload Voices'),
    '#size' => 40,
    '#description' => 'Allowed extensions: zip',
  );
  
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Import'),
  );
  $form['#attributes'] = array('enctype' => "multipart/form-data"); 
  return $form;
}

function voipvoice_import_voice_submit($form, &$form_state) {
  // Convert the import formatted text back into a $content array.
  // Return if errors generated or not an array.
  // Use '@' to suppress errors about undefined constants in the macro.
  @eval('$import = ' . $form_state['values']['import']);
  
  // Preliminary error trapping, must have valid arrays to work with.
  if (!isset($import) || !is_array($import)) {
    form_set_error('import', t('The import data is not valid import text.'));
    return;
  }
  
  $lexicon = $import['lexicon'];
  $voice = $import['voice'];
  $phrases = $import['phrases'];

  $res = voipvoice_create_lexicon($lexicon);
  if(!$res) {
    drupal_set_message(t('Lexicon @lexicon not imported because it already exists.', array('@lexicon' => $lexicon['lexicon'])), 'error');
  }
  else {
    drupal_set_message(t('Imported lexicon @lexicon.', array('@lexicon' => $lexicon['lexicon'])));
  }
  
  $res = voipvoice_create_voice($voice);
  if(!$res) {
    drupal_set_message(t('Voice @voice not imported because it already exists.', array('@voice' => $voice['name'])), 'error');
  }
  else {
    drupal_set_message(t('Imported voice @voice.', array('@voice' => $voice['name'])));
  }
  //Import phrases
  voipvoice_import_phrases($phrases);
  
  //Unzip voices
   if (!empty($_FILES['files']['tmp_name']['import_voices_zip'])) {
     voipvoice_import_voices($_FILES['files']['tmp_name']['import_voices_zip'], $voice['name']);
   }
   drupal_set_message(t('You can view your imported voice ').l('here','admin/settings/voipvoice/voices/recordings/'.$voice['name']));
}

function voipvoice_export_voice(&$form_state, $voice_code) {
  $lexicon_name = voipvoice_get_voice_lexicon($voice_code);
  $export['lexicon'] = voipvoice_get_lexicon($lexicon_name);
  $export['voice'] = voipvoice_get_voice($voice_code);
  $export['phrases'] = voipvoice_get_phrases($voice_code);
  
  $export_code = var_export($export, true);
  $form['export'] = array(
    '#prefix' => '<div><b>Step 1: </b>'.t('The export created by this process can be copied and pasted as an import into the other database.').'</div>',
    '#type' => 'textarea',
    '#title' => t('Export data'),
    '#description' => t('Copy the export text and paste it into another site using the VoIP Voice import function.'),
    '#cols' => 60,
    '#rows' => max(40, sizeof($export)),
    '#value' => $export_code.';',
    '#suffix' => '<div><b>Step 2: </b>'.l('Download voices', 'admin/settings/voipvoice/export-zip/'.$voice_code).' and upload them in import process.</div>'
  );
  
  return $form;
}



function voipvoice_voice_advance($voice_code, $pid) {
  $phrase = db_fetch_array(db_query("SELECT * FROM {voipvoice_phrases} WHERE pid=%d", $pid));
  $langcode = voipvoice_get_language($voice_code);
  $args = unserialize($phrase['args']);
  $translated_string = t($phrase['phrase'], array(), $langcode);
  
   $output .= "<div><b>pid:</b> ".$phrase['pid']."</div>";
   $output .= "<div><b>voice:</b> ".$voice_code."</div>";
   $output .= "<div><b>Original phrase:</b> ".$phrase['phrase']."</div>";
   $output .= "<div><b>Translated phrase:</b> ".$translated_string."</div>";
   
  $args = unserialize($phrase['args']);
  if (is_array($args) && !empty($args)) {
      //String with arguments
      $token = '_vio_' . mt_rand();
      $tokenized_keys = array();
      foreach(array_keys($args) as $key) {
          $tokenized_keys[$key] = "$token$key$token";
      }
      $tokenized_string = strtr($translated_string, $tokenized_keys);
      // then split the string into an array of text chunks and arguments
      $speech_array = explode($token, $tokenized_string);
      $i=1;
      foreach ($speech_array as $index => $speech_phrase) {
        if($speech_phrase && !(($speech_phrase{0} == '%') && (array_key_exists($speech_phrase, $args)))) {
          $speech_phrase = trim($speech_phrase);
          $phrase_hash = md5($speech_phrase);
          $output .= "<div><b>Phrase hash for string $i:</b> ".$phrase_hash."</div>";
          $phrase_file_name = voipvoice_recording_exists($voice_code, $phrase_hash);
          //check if there is a voice
          if ($phrase_file_name) {
             $temp_output .= "<div><b>Audio $i available:</b> Yes</div>";
             $temp_output .= "<div><b>Audio $i created:</b> ".date("F d Y H:i:s.", filemtime($phrase_file_name))."</div>";
             $temp_output .= "<div><b>Audio $i last accessed:</b> ".date("F d Y H:i:s.", fileatime($phrase_file_name))."</div>";
          }
          $i++;
        }
        
      }
      
      if ($temp_output) {
        $output .= $temp_output;
      }
      else {
        $output .= "<div><b>Audio available:</b> No</div>";
      }
  }
  else {
    //no arguments
    $phrase_hash = md5($translated_string);
    $output .= "<div><b>Phrase hash:</b> ".$phrase_hash."</div>";
    $phrase_file_name = voipvoice_recording_exists($voice_code, $phrase_hash);
    if ($phrase_file_name) {
      $output .= "<div><b>Audio available:</b> Yes</div>";
      $output .= "<div><b>Audio created:</b> ".date("F d Y H:i:s.", filemtime($phrase_file_name))."</div>";
      $output .= "<div><b>Last accessed:</b> ".date("F d Y H:i:s.", fileatime($phrase_file_name))."</div>";
    }
    else {
      $output .= "<div><b>Audio available:</b> No</div>";
    }
    

  }

   $output.=l("Go back","admin/settings/voipvoice/voices/recordings/".$voice_code);
   return $output;
}

function voipvoice_lexicons() {
  $items = array();  
  $res = db_query("SELECT lexicon FROM {voipvoice_lexicons}");
  
  while($obj = db_fetch_object($res)) {
    $items[$obj->lexicon] = check_plain($obj->lexicon);
  }
  return $items;
}

function voipvoice_general_settings_form(&$form_state) {
  /*$voices = array_keys(voipvoice_get_voices());
  foreach($voices as $voice) {
    $voices_list[$voice] =$voice;
  }
  $form['voipvoice_default_man'] = array(
    '#type' => 'select',
    '#title' => t('Default Man Voice'),
    '#options' => $voices_list,
    '#default_value' => variable_get('voipvoice_default_man', ''),
  );
  
  $form['voipvoice_default_woman'] = array(
    '#type' => 'select',
    '#title' => t('Default Woman Voice'),
    '#options' => $voices_list,
    '#default_value' => variable_get('voipvoice_default_woman', ''),
  );
  */
  $form['voipvoice_allowed_extensions'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Allowed Audio extensions'),
    '#description' => t('This audio extensions will be searched for in voice recordings'),
    '#options' => array('wav' => 'wav', 'mp3'=>'mp3'),
    '#default_value' => variable_get('voipvoice_allowed_extensions', array('wav'=>'wav')),
  );
  
  return system_settings_form($form);
}

function voipvoice_add_phrase_form(&$form_state, $lexicon) {
  $form_state['data']['lexicon'] = $lexicon;
  $form['phrase'] = array(
    '#type' => 'textfield',
    '#title' => t('Phrase'),
    '#default_value' => '',
    '#required' => TRUE,
  );
  
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Save'),
  );
  
  $form['back'] = array(
    '#type' => 'button', 
    '#value' => t('Go back'),
    '#attributes' => array('onClick' => 'location.replace("'. base_path() .'admin/settings/voipvoice/lexicons"); return false;'),
  );
  
  return $form;
}

function voipvoice_add_phrase_form_submit($form,&$form_state) {
  //Add phrase to the table
  $lexicon = $form_state['data']['lexicon'];
  $phrase = $form_state['values']['phrase'];
  _voipvoice_add_phrase($lexicon, $phrase);
  drupal_set_message('Phrase added sucessfully');
}

function voipvoice_add_lexicon(&$form_state, $lexicon = NULL) {
  
  if ($lexicon) {
    $lexicon_data = db_fetch_array(db_query("SELECT * FROM {voipvoice_lexicons} WHERE lexicon='%s'", $lexicon));
    $description = $lexicon_data['description'];
    $form_state['old_lexicon'] = $lexicon;
    $form_state['isupdate'] = TRUE;
  }
  
  $form['lexicon'] = array(
    '#type' => 'textfield',
    '#title' => t('Lexicon Name'),
    '#required' => TRUE,
    '#default_value' => $lexicon,
  );
  
  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Description'),
    '#default_value' => $description,
  );
  
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Save'),
  );
  return $form;
}

function voipvoice_add_lexicon_submit(&$form, &$form_state) {
  $lexicon = $form_state['values']['lexicon'];
  $description = $form_state['values']['description'];
  $status = 'status';
  if ($form_state['isupdate']) {
    $old_lexicon = $form_state['old_lexicon'];
    $res = db_query("UPDATE {voipvoice_lexicons} SET lexicon ='%s', description='%s' WHERE lexicon='%s'", $lexicon, $description, $old_lexicon);
    if ($res) {
      $res = db_query("UPDATE {voipvoice_voices} SET lexicon ='%s' WHERE lexicon='%s'", $lexicon, $old_lexicon);
    }
    if ($res) {
      $res = db_query("UPDATE {voipvoice_phrases} SET lexicon ='%s' WHERE lexicon='%s'", $lexicon, $old_lexicon);
    }
    if($res) {
      $message = t('Lexicon sucessfully updated.');
    }
    else {
     $message = t('Lexicon couldn\'t be updated. Please try again later.');
      $status = 'error';
    }
  }
  else {
    $res = db_query("INSERT INTO {voipvoice_lexicons} (lexicon, description) VALUES('%s', '%s') ", $lexicon, $description);
    if($res) {
    $message = t('New Lexicon added.');
    }
    else {
      $message = t('New Lexicon couldn\'t be added. Please try again later.');
      $status = 'error';
    }
  }
 
  
  //TODO: Update voice_phrases?
  
  drupal_set_message($message, $status);
  $form_state['redirect'] = 'admin/settings/voipvoice/lexicons';
}

function voipvoice_manage_lexicons() {
  $res = db_query("SELECT * FROM {voipvoice_lexicons}");
  $header = array(t('Name'), t('Settings'), t('View phrases'),t('Add phrase'),t('Delete lexicon'));
  $rows = array();
  while ($lexicon = db_fetch_array($res)) {
     $rows[] = array(
        check_plain($lexicon['lexicon']),
        l('settings', 'admin/settings/voipvoice/lexicons/edit/'.$lexicon['lexicon']),
        l('view phrases', 'admin/settings/voipvoice/lexicons/phrases/'.$lexicon['lexicon']),
        l('add phrase', 'admin/settings/voipvoice/lexicons/add-phrase/'.$lexicon['lexicon']),
        l('delete', 'admin/settings/voipvoice/lexicons/delete/'.$lexicon['lexicon']),
      );
  }

  $output .= theme('table', $header, $rows);

  return $output;
}

function voipvoice_lexicon_phrases($lexicon) {
  $header = array(
     array(
      'data' => t('Original Phrase'),
      'field' => 'phrase',
      'sort'  => 'asc',
      ), 
     t('Delete')
   );
  //db query
  $sql = "SELECT * FROM {voipvoice_phrases} WHERE lexicon='%s'".tablesort_sql($header);
  //set limit for pager
  $limit = 25;
  $res = pager_query($sql, $limit, 0, NULL, $lexicon);
  $rows = array();
  while ($phrase = db_fetch_array($res)) {
    $rows[] = array(
        $phrase['phrase'],
        l('delete', 'admin/settings/voipvoice/lexicons/delete-phrase/'.$phrase['pid']),
      );
  }
  
  
  $output .= theme('table', $header, $rows);
  $output .= theme('pager', NULL, $limit, 0);
  
  return $output;
}

/*Delete lexicon*/
function voipvoice_delete_lexicon_form(&$form_state, $lexicon) {
  $form_state['data']['lexicon'] = $lexicon;
  $form['message'] = array(
    '#value' => t('Are you sure you wish to delete lexicon %lexicon. This will delete all the phrases and voices belonging to the lexicon as well.'.'<br/>', 
     array('%lexicon' => $lexicon)),
  );
  $form['submit'] = array('#type' => 'submit', '#value' => t('Delete'));	

  $form['buttons']['cancel'] = array(
    '#type' => 'button',
    '#weight' => 2,
    '#attributes' => array('onClick' => 'location.replace("'. referer_uri() .'"); return false;'),
    '#value' => t('Cancel'),
  );
  return $form;
}

function voipvoice_delete_lexicon_form_submit($form, &$form_state) {
  $lexicon = $form_state['data']['lexicon'];
  voipvoice_delete_lexicon($lexicon);
  $form_state['redirect'] = 'admin/settings/voipvoice/lexicons';
}

/*Delete phrase*/
function voipvoice_delete_phrase(&$form_state, $pid) {
  $form_state['data']['pid'] = $pid;
  $form['message'] = array(
    '#value' => t('Are you sure you wish to delete phrase? This will delete all the phrase recordings as well.').'<br/>',
  );
  
  $form['submit'] = array('#type' => 'submit', '#value' => t('Delete'));	
  $form['buttons']['cancel'] = array(
    '#type' => 'button',
    '#weight' => 2,
    '#attributes' => array('onClick' => 'location.replace("'. referer_uri() .'"); return false;'),
    '#value' => t('Cancel'),
  );
  return $form;
}

function voipvoice_delete_phrase_submit($form, &$form_state) {
  $pid = $form_state['data']['pid'];
  
  $phrase = db_fetch_array(db_query("SELECT * FROM {voipvoice_phrases} WHERE pid=%d", $pid));
  $extensions = variable_get('voipvoice_allowed_extensions', array('wav' => 'wav', 'mp3' => '0'));
 
  $res = db_query("SELECT name FROM {voipvoice_voices} WHERE lexicon='%s'", $phrase['lexicon']);
  while ($voice_code = db_result($res)) {
    //Delete all recordings of phrase
    $voice_dir = _voipvoice_get_voice_dir($voice_code);
    foreach($extensions as $ext) {
      if($ext) {
        $delete_file = $voice_dir . $phrase['hash'] . "." . $ext;
        @unlink($delete_file); 
      }
    }
  }
  db_query("DELETE FROM {voipvoice_phrases} WHERE pid=%d", $pid);
  drupal_set_message('Phrase sucessfully deleted');
  $form_state['redirect'] = 'admin/settings/voipvoice/lexicons/phrases/'.$phrase['lexicon'];
}

/*Delete voice*/
function voipvoice_delete_voice_form(&$form_state, $voice_code) {
  $form_state['data']['voice_code'] = $voice_code;
  $form['message'] = array(
    '#value' => t('Are you sure you wish to delete voice %voice_code and all its recordings?', 
    array('%voice_code' => $voice_code)).'<br/>',
  );
  
  $form['submit'] = array('#type' => 'submit', '#value' => t('Delete'));	
  $form['buttons']['cancel'] = array(
    '#type' => 'button',
    '#weight' => 2,
    '#attributes' => array('onClick' => 'location.replace("'. referer_uri() .'"); return false;'),
    '#value' => t('Cancel'),
  );
  return $form;
}

function voipvoice_delete_voice_form_submit($form, &$form_state) {
  $voice_code = $form_state['data']['voice_code'];
  voipvoice_delete_voice($voice_code);
  $form_state['redirect'] = 'admin/settings/voipvoice/voices';
}

function _voip_voice_delete_dir($dirPath) {
    if (! is_dir($dirPath)) {
      return;
    }
    if (substr($dirPath, strlen($dirPath) - 1, 1) != '/') {
        $dirPath .= '/';
    }
    $files = glob($dirPath . '*', GLOB_MARK);
    foreach ($files as $file) {
        if (is_dir($file)) {
            _voip_voice_delete_dir($file);
        } else {
            unlink($file);
        }
    }
    rmdir($dirPath);
}

//Helper function to create zip archive
function _voipvoice_create_zip($src)
{
  if (substr($src,-1)==='/') {
    $src=substr($src,0,-1);
  }

  $zipname=realpath('./'.file_directory_path()).DIRECTORY_SEPARATOR.'voipvoice-export-'.time().'.zip';
  //$zipname=realpath('./'.file_directory_temp()).DIRECTORY_SEPARATOR.'voipvoice-export-'.time().'.zip';

  $zip = new ZipArchive;
  $res = $zip->open($zipname, ZipArchive::CREATE);
  if($res !== TRUE) {
    drupal_set_message('Error: Unable to create zip file', 'error');
    return FALSE;
  }
            
  $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($src));	
  // iterate over the directory
  // add each file found to the archive
  foreach ($iterator as $key=>$value) {
    $filename=basename($key);
    $zip->addFile(realpath($key), $filename);
  }
  
  $zip->close();
  return $zipname;
}

/*Serve zip file of exported VoIP Voices*/
function voipvoice_export_voice_zip($voice_code) {
  $voice_path = file_create_path(file_directory_path() . '/' . variable_get('voipvoice_directory', 'voipvoice').'/'.$voice_code);
  $zipname = _voipvoice_create_zip($voice_path);
  if ($zipname) {
    header('Content-disposition: attachment; filename="'.$voice_code.'.zip"');
    header('Content-type: application/zip');
    readfile($zipname);
    exit;
  }
}