<?php

define('VOIPNUMBER_ACTIVE', 1);
define('VOIPNUMBER_VERIFIED', 2);
define('VOIPNUMBER_DEFAULT', 4);

define('VOIPNUMBER_PSTN', 1);
define('VOIPNUMBER_SIP', 2);
define('VOIPNUMBER_SMS', 3);
define('VOIPNUMBER_MOBILE', 4);
define('VOIPNUMBER_WORK', 5);
define('VOIPNUMBER_HOME', 6);
define('VOIPNUMBER_FAX', 7);

module_load_include('inc', 'voipnumber', 'voipnumber');

/*Custom hooks*/
/**
 * Implementation of hook_get_voip_numbers().
 *
 * Returns numbers provided by voipnumber module (voipnumber CCK and voipnumber user profile)
 */
function voipnumber_get_voip_numbers($id, $type) {
  $numbers = array();
  switch ($type) {
    case 'user':
      $res = db_query("SELECT * FROM {voipnumber} WHERE uid=%d", $id);
      $numbers = array();
      while($voipnumber_data = db_fetch_array($res)) {
        $numbers[] = new VoipNumber($voipnumber_data);
      }
      return $numbers;
      break;
    case 'node':
      $res = db_query("SELECT * FROM {voipnumber} WHERE nid=%d", $id);
      $numbers = array();
      while($voipnumber_data = db_fetch_array($res)) {
        $numbers[] = new VoipNumber($voipnumber_data);
      }
      return $numbers;
      break;
    case 'number':
      $res = db_query("SELECT * FROM {voipnumber} WHERE phone_number='%s'", $id);
      $numbers = array();
      while($voipnumber_data = db_fetch_array($res)) {
        $numbers[] = new VoipNumber($voipnumber_data);
      }
      return $numbers;
      break;
    case 'nids':
      $res = db_query("SELECT DISTINCT(nid) FROM {voipnumber} WHERE phone_number='%s'", $id);
      $nids = array();
      while($row = db_fetch_array($res)) {
        $nids[$row['nid']] = $row['nid'];
      }
      return $nids;
      break;
    case 'uids':
      $res = db_query("SELECT DISTINCT(uid) FROM {voipnumber} WHERE phone_number='%s'", $id);
      $uids = array();
      while($row = db_fetch_array($res)) {
        $uids[$row['uid']] = $row['uid'];
      }
      return $uids;
      break;
  }
}

/*
 *
 * $number_data['phone_number'] = '+385998844502';
$vn = new VoipNumber($number_data);

$vn->setName('tamer');
$vn->setCountryName('Croatia');
$vn->setType(VOIPNUMBER_MOBILE);
$vn->setDefault(TRUE);
$vn->setUid(1);
$vn->setNid(22);
$vn = $vn->save();
$vn->setName('tamer2');
$vn->save();
print $vn->getName();
print '<br/>';
print $vn->getCountryName();
print '<br/>';
print $vn->getNumber();
print '<br/>';
print $vn->getType();
print '<br/>';
print $vn->getStatus();
print '<br/>';
print $vn->getUid();
print '<br/>';
print $vn->getNid();
print '<br/>';
print $vn->isActive();
print '<br/>';
print $vn->isVerified();
print '<br/>';
print $vn->isDefault();
print '<br/>';

*/
